import os

# Project project paths (see vxprojinfo.py for the available info)
vcxprojserver = '../game/server/server_hl2mp-2010.vcxproj'
vcxprojclient = '../game/client/client_hl2mp-2010.vcxproj'

# Automatically add all python module files to the project files
# Backup before using!
autoupdatevxproj = False
addpythonfiles = False

# Paths to be searched by Python for modules containing the binding code
searchpaths = [
    os.path.normpath('../game/client/python/modules/'),
    os.path.normpath('../game/server/python/modules/'),
    os.path.normpath('../game/shared/python/modules/'),
]

# Output paths for generated binding code
client_path = os.path.normpath('../game/client/python/modules/autogenerated/')
server_path = os.path.normpath('../game/server/python/modules/autogenerated/')
shared_path = os.path.normpath('../game/shared/python/modules/autogenerated/')

# The list of modules
# The parse code looks in the above paths
modules = [
    # Base
    ('srcbuiltins', 'SrcBuiltins'),
    
    # Game
    ('_entities', 'Entities'),
    ('_entitiesmisc', 'EntitiesMisc'),
]

'''('srcbase', 'SrcBase'),
('_vmath', 'VMath'),
('_entities', 'Entities'),
('_entities_misc', 'EntitiesMisc'),
('_gameinterface', 'GameInterface'),
('_utils', 'Utils'),
('_physics', 'Physics'),
('_sound', 'Sound'),
('_particles', 'Particles'),
('materials', 'Materials'),
('_animation', 'Animation'),
('_te', 'TE'),
('_fow', 'FOW'),

# # Client
('isteam', 'ISteam'),
('_input', 'Input'),
('_vgui', 'VGUI'),
('_vguicontrols', 'VGUIControls'),
#('_awesomium', 'Awesomium'),
('_cef', 'CEF'),

# # Game
('_gamerules', 'GameRules'),
('unit_helper', 'UnitHelper'),

# # Misc
('_navmesh', 'NavMesh'),
('_ndebugoverlay', 'NDebugOverlay'),
('vprof', 'VProf'),
('_srctests', '_SrcTests'),
('matchmaking', 'MatchMaking'),'''

# Base files (in case you want to make use automatically updating the vcxproj)
pythonfiles_shared = [
    '../shared/python/srcpy.cpp',
    '../shared/python/srcpy.h',
    '../shared/python/srcpy_srcbuiltins.cpp',
    '../shared/python/srcpy_srcbuiltins.h',
    '../shared/python/srcpy_class_shared.cpp',
    '../shared/python/srcpy_class_shared.h',
    '../shared/python/srcpy_entities.cpp',
    '../shared/python/srcpy_entities.h',
    '../shared/python/srcpy_networkvar.cpp',
    '../shared/python/srcpy_networkvar.h',
    '../shared/python/srcpy_usermessage.cpp',
    '../shared/python/srcpy_usermessage.h',
]

pythonfiles_client = [
    'python/srcpy_client_class.cpp',
    'python/srcpy_client_class.h',
]

pythonfiles_server = [
    'python/srcpy_server_class.cpp',
    'python/srcpy_server_class.h',
]

