// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef C_BaseCombatCharacter_hpp__pyplusplus_wrapper
#define C_BaseCombatCharacter_hpp__pyplusplus_wrapper

void register_C_BaseCombatCharacter_class();

#endif//C_BaseCombatCharacter_hpp__pyplusplus_wrapper

