// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef C_BaseEntity_hpp__pyplusplus_wrapper
#define C_BaseEntity_hpp__pyplusplus_wrapper

void register_C_BaseEntity_class();

#endif//C_BaseEntity_hpp__pyplusplus_wrapper

