// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef C_BaseAnimating_hpp__pyplusplus_wrapper
#define C_BaseAnimating_hpp__pyplusplus_wrapper

void register_C_BaseAnimating_class();

#endif//C_BaseAnimating_hpp__pyplusplus_wrapper

