// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef C_BaseGrenade_hpp__pyplusplus_wrapper
#define C_BaseGrenade_hpp__pyplusplus_wrapper

void register_C_BaseGrenade_class();

#endif//C_BaseGrenade_hpp__pyplusplus_wrapper

