// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef C_BasePlayer_hpp__pyplusplus_wrapper
#define C_BasePlayer_hpp__pyplusplus_wrapper

void register_C_BasePlayer_class();

#endif//C_BasePlayer_hpp__pyplusplus_wrapper

