// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef IClientUnknown_hpp__pyplusplus_wrapper
#define IClientUnknown_hpp__pyplusplus_wrapper

void register_IClientUnknown_class();

#endif//IClientUnknown_hpp__pyplusplus_wrapper

