// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef IClientEntity_hpp__pyplusplus_wrapper
#define IClientEntity_hpp__pyplusplus_wrapper

void register_IClientEntity_class();

#endif//IClientEntity_hpp__pyplusplus_wrapper

