"Resource/UI/HudPasstimeTeamScore.res"
{
	"HudTeamScore"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"HudPasstimeTeamScore"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"0"
		"wide"				"f0"
		"tall"				"f0"
		"visible"			"1"
		"enabled"			"1"
	}
	"GreyBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"GreyBG"
		"xpos"			"cs-0.5"
		"ypos"			"c-236"
		"xpos_minmode"	"c-92"
		"ypos_minmode"	"r68"
		"zpos"			"0"
		"wide"			"156"
		"tall"			"26"
		"wide_minmode"	"184"
		"tall_minmode"	"64"
		"visible"		"1"
		"enabled"		"1"
		//"image"			"../hud/greybg"
		"scaleImage"	"1"	
		"bgcolor_override" "32 32 32 200"


	}
			"LeftSideBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"LeftSideBG"
		"xpos"			"-2"
		"ypos"			"-2"
		"xpos_minmode"	"c-92"
		"ypos_minmode"	"r68"
		"zpos"			"1"
		"wide"			"76"
		"tall"			"22"
		"wide_minmode"	"184"
		"tall_minmode"	"64"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/objectives_flagpanel_bg_left"
		"scaleImage"	"1"	
		"pin_to_sibling" "GreyBG"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPLEFT"
	}
		
	"RightSideBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"RightSideBG"
		"xpos"			"0"
		"ypos"			"0"
		"xpos_minmode"	"c-92"
		"ypos_minmode"	"r68"
		"zpos"			"1"
		"wide"			"76"
		"tall"			"22"
		"wide_minmode"	"184"
		"tall_minmode"	"64"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/objectives_flagpanel_bg_right"
		"scaleImage"	"1"	
		"pin_to_sibling" "LeftSideBG"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPRIGHT"

	}

	"OutlineBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"OutlineBG"
		"xpos"			"c-140"
		"ypos"			"r81"
		"xpos_minmode"	"c-92"
		"ypos_minmode"	"r68"
		"zpos"			"2"
		"wide"			"280"
		"tall"			"80"
		"wide_minmode"	"184"
		"tall_minmode"	"64"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/objectives_flagpanel_bg_outline"
		"scaleImage"	"1"	
	}
	
	"BlueScore"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BlueScore"
		"xpos"			"0"
		"ypos"			"0"
		"xpos_minmode"	"c-80"
		"ypos_minmode"	"r50"
		"zpos"			"8"
		"wide"			"26"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%bluescore%"
		"font"			"HudFontMediumBigBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"255 255 246 255"
		"pin_to_sibling" 							"LeftSideBG"
		"pin_corner_to_sibling" "PIN_TOPRIGHT"
		"pin_to_sibling_corner" "PIN_TOPRIGHT"
	}	
		
	"BlueScoreShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BlueScoreShadow"
		"xpos"			"-2"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"26"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%bluescore%"
		"font"			"HudFontMediumBigBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"Black"
		
		"pin_to_sibling"		"BlueScore"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
	}	
							
	"RedScore"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedScore"
		"xpos"			"0"
		"ypos"			"0"
		"xpos_minmode"	"c2"
		"ypos_minmode"	"r50"
		"zpos"			"8"
		"wide"			"25"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%redscore%"
		"font"			"HudFontMediumBigBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"255 255 246 255"		
		"pin_to_sibling" 							"RightSideBG"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPLEFT"
	}	
		
	"RedScoreShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedScoreShadow"
		"xpos"			"-2"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"25"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%redscore%"
		"font"			"HudFontMediumBigBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"Black"	

		"pin_to_sibling"		"RedScore"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"		
	}

	"BluTeamName"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BluTeamName"
		"xpos"			"-5"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"BLU"
		"font"			"HudFontMediumBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"255 255 246 255"	

		"pin_to_sibling"		"LeftSideBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"	
	}
	"BluTeamNameShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BluTeamNameShadow"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"BLU"
		"font"			"HudFontMediumBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"Black"	

		"pin_to_sibling"		"BluTeamName"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"	
	}

	"RedTeamName"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedTeamName"
		"xpos"			"-5"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"RED"
		"font"			"HudFontMediumBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"255 255 246 255"	

		"pin_to_sibling"		"RightSideBG"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"	
	}
	"RedTeamNameShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedTeamNameShadow"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"RED"
		"font"			"HudFontMediumBold"
		"font_minmode"	"HudFontMedium"
		"fgcolor"		"Black"	

		"pin_to_sibling"		"RedTeamName"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"	
	}
	"PlayingToCluster"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"PlayingToCluster"
		"xpos"				"9999"
		"ypos"				"17"
		"zpos"				"10"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"0"
		"enabled"			"0"

		"PlayingTo"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PlayingTo"
			"xpos"			"c-70"
			"ypos"			"r57"
			"zpos"			"4"
			"wide"			"140"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#TF_PlayingTo"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"HudFontSmall"
			"fgcolor"		"TanLight"
		}	
				
		"PlayingToBG"
		{
			"ControlName"	"CTFImagePanel"
			"fieldName"		"PlayingToBG"
			"xpos"			"c-50"
			"ypos"			"r58"
			"zpos"			"3"
			"wide"			"100"
			"tall"			"32"
			"visible"		"1"
			"enabled"		"1"
			"image"			"../hud/objectives_flagpanel_bg_playingto"
			"image_hidef"	"../hud/objectives_flagpanel_bg_playingto_hidef"
			"scaleImage"	"1"	
		}
	}
}
