"Resource/UI/HudPasstimeTeamScore.res"
{
	"HudTeamScore"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"HudPasstimeTeamScore"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"0"
		"wide"				"f0"
		"tall"				"f0"
		"visible"			"1"
		"enabled"			"1"
	}

	"GreyBG"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"GreyBG"
		"xpos"			"cs-0.5"
		"ypos"			"c-236"
		"xpos_minmode"	"cs-0.5"
		"ypos_minmode"	"c-236"
		"zpos"			"0"
		"wide"			"156"
		"tall"			"26"
		"wide_minmode"	"57"
		"tall_minmode"	"26"
		"visible"		"1"
		"enabled"		"1"
		//"image"			"../hud/greybg"
		"scaleImage"	"1"	
		"bgcolor_override" "PFGrey"
	}

	"LeftSideBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"LeftSideBG"
		"xpos"			"-2"
		"ypos"			"-2"
		"xpos_minmode"	"-2"
		"ypos_minmode"	"-2"
		"zpos"			"1"
		"wide"			"76"
		"tall"			"22"
		"wide_minmode"	"27"
		"tall_minmode"	"22"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/objectives_flagpanel_bg_left"
		"image_minmode"	"../hud/PFBlue"
		"scaleImage"	"1"	
		"scaleImage_minmode" "1"
		"pin_to_sibling" "GreyBG"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPLEFT"
	}
		
	"RightSideBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"RightSideBG"
		"xpos"			"0"
		"ypos"			"0"
		"xpos_minmode"	"0"
		"ypos_minmode"	"0"
		"zpos"			"1"
		"wide"			"76"
		"tall"			"22"
		"wide_minmode"	"27"
		"tall_minmode"	"22"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/objectives_flagpanel_bg_right"
		"image_minmode"	"../hud/PFRed"
		"scaleImage"	"1"	
		"scaleImage_minmode" "1"
		"pin_to_sibling" "LeftSideBG"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPRIGHT"

	}

	"OutlineBG"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"OutlineBG"
		"xpos"			"c-140"
		"ypos"			"r81"
		"xpos_minmode"	"c-92"
		"ypos_minmode"	"r68"
		"zpos"			"2"
		"wide"			"280"
		"tall"			"80"
		"wide_minmode"	"184"
		"tall_minmode"	"64"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/objectives_flagpanel_bg_outline"
		"scaleImage"	"1"	
	}
	
	"BlueScore"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BlueScore"
		"xpos"			"0"
		"ypos"			"0"
		"xpos_minmode"	"-1"
		"ypos_minmode"	"0"
		"zpos"			"8"
		"wide"			"26"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%bluescore%"
		"font"			"MontserratBlack34"
		"font_minmode"	"MontserratBlack34"
		"fgcolor"		"PFWhite"
		"pin_to_sibling" 							"LeftSideBG"
		"pin_corner_to_sibling" "PIN_TOPRIGHT"
		"pin_to_sibling_corner" "PIN_TOPRIGHT"
	}	
		
	"BlueScoreShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BlueScoreShadow"
		"xpos"			"-2"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"26"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%bluescore%"
		"font"			"MontserratBlack34"
		"font_minmode"	"MontserratBlack34"
		"fgcolor"		"PFGrey"
		
		"pin_to_sibling"		"BlueScore"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"
	}	
							
	"RedScore"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedScore"
		"xpos"			"0"
		"ypos"			"0"
		"xpos_minmode"	"-1"
		"ypos_minmode"	"0"
		"zpos"			"8"
		"wide"			"25"
		"tall"			"22"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%redscore%"
		"font"			"MontserratBlack34"
		"font_minmode"	"MontserratBlack34"
		"fgcolor"		"PFWhite"		
		"pin_to_sibling" 							"RightSideBG"
		"pin_corner_to_sibling" "PIN_TOPLEFT"
		"pin_to_sibling_corner" "PIN_TOPLEFT"
	}	
		
	"RedScoreShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedScoreShadow"
		"xpos"			"-2"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"25"
		"tall"			"24"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%redscore%"
		"font"			"MontserratBlack34"
		"font_minmode"	"MontserratBlack34"
		"fgcolor"		"PFGrey"	

		"pin_to_sibling"		"RedScore"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"		
	}

	"BluTeamName"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BluTeamName"
		"xpos"			"-5"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"visible_minmode" "0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"BLU"
		"font"			"MontserratBlack26"
		"font_minmode"	"MontserratBlack26"
		"fgcolor"		"PFWhite"	

		"pin_to_sibling"		"LeftSideBG"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"	
	}
	"BluTeamNameShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"BluTeamNameShadow"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"visible_minmode" "0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"BLU"
		"font"			"MontserratBlack26"
		"font_minmode"	"MontserratBlack26"
		"fgcolor"		"Black"	

		"pin_to_sibling"		"BluTeamName"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"	
	}

	"RedTeamName"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedTeamName"
		"xpos"			"-5"
		"ypos"			"0"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"visible_minmode" "0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"RED"
		"font"			"MontserratBlack26"
		"font_minmode"	"MontserratBlack26"
		"fgcolor"		"PFWhite"	

		"pin_to_sibling"		"RightSideBG"
		"pin_corner_to_sibling"	"PIN_TOPRIGHT"
		"pin_to_sibling_corner"	"PIN_TOPRIGHT"	
	}
	"RedTeamNameShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"RedTeamNameShadow"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"7"
		"wide"			"41"
		"tall"			"23"
		"visible"		"1"
		"visible_minmode" "0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"RED"
		"font"			"MontserratBlack26"
		"font_minmode"	"MontserratBlack26"
		"fgcolor"		"Black"	

		"pin_to_sibling"		"RedTeamName"
		"pin_corner_to_sibling"	"PIN_TOPLEFT"
		"pin_to_sibling_corner"	"PIN_TOPLEFT"	
	}
	"PlayingToCluster"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"PlayingToCluster"
		"xpos"				"9999"
		"ypos"				"17"
		"zpos"				"10"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"0"
		"enabled"			"0"

		"PlayingTo"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PlayingTo"
			"xpos"			"c-70"
			"ypos"			"r57"
			"zpos"			"4"
			"wide"			"140"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#TF_PlayingTo"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"MontserratSemibold16"
			"fgcolor"		"TanLight"
		}
		
		"PlayingToShadow"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"PlayingToShadow"
			"xpos"			"c-69"
			"ypos"			"r55"
			"zpos"			"4"
			"wide"			"140"
			"tall"			"30"
			"visible"		"1"
			"enabled"		"1"
			"labelText"		"#TF_PlayingTo"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"font"			"MontserratSemibold16"
			"fgcolor"		"TanDark"
				
			"PlayingToBG"
			{
				"ControlName"	"CTFImagePanel"
				"fieldName"		"PlayingToBG"
				"xpos"			"c-60"
				"ypos"			"r60"
				"zpos"			"3"
				"wide"			"120"
				"tall"			"36"
				"visible"		"0"
				"enabled"		"1"
				"image"			"../hud/objectives_flagpanel_bg_playingto"
				"image_hidef"	"../hud/objectives_flagpanel_bg_playingto_hidef"
				"scaleImage"	"1"	
			}
		}
	}
}
