#include "shaderlib/cshader.h"
class debugmorphaccumulator_vs30_Static_Index
{
public:
	debugmorphaccumulator_vs30_Static_Index( )
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderStaticTest_debugmorphaccumulator_vs30 0
class debugmorphaccumulator_vs30_Dynamic_Index
{
public:
	debugmorphaccumulator_vs30_Dynamic_Index()
	{
	}
	int GetIndex()
	{
		// Asserts to make sure that we aren't using any skipped combinations.
		// Asserts to make sure that we are setting all of the combination vars.
#ifdef _DEBUG
#endif // _DEBUG
		return 0;
	}
};
#define shaderDynamicTest_debugmorphaccumulator_vs30 0
