#!/usr/bin/python
import datetime, sys, subprocess, platform

def main():
  date = datetime.datetime.now().isoformat(timespec="seconds")
  git_subproc = subprocess.run("git describe --always --dirty=\" (modified)\"", encoding="UTF-8", shell=True, check=True, capture_output=True)
  info = git_subproc.stdout.removesuffix("\n")
  uname = platform.uname()
  os = uname[0] + " " + uname[2]
  # print(date, info, uname[0], uname[2])
  print(
    '// This file was generated by devtools/genbuildinfo.py .\n'
    '// Do ***not*** edit it by hand.\n'
    '\n'
    f'const char* g_szbuildInfo = "p4ss {info} at {date} ({os})";\n'
    f'const char* g_szbuildCommit = "{info}";\n'
    f'const char* g_szbuildDate = "{date}";\n'
    f'const char* g_szbuildOs = "{os}";\n'
  )


if __name__ == "__main__":
  main()