// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef _entities_free_functions_hpp__pyplusplus_wrapper
#define _entities_free_functions_hpp__pyplusplus_wrapper

void register_free_functions();

#endif//_entities_free_functions_hpp__pyplusplus_wrapper

