// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef CBaseCombatCharacter_hpp__pyplusplus_wrapper
#define CBaseCombatCharacter_hpp__pyplusplus_wrapper

void register_CBaseCombatCharacter_class();

#endif//CBaseCombatCharacter_hpp__pyplusplus_wrapper

