// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef CBaseFlex_hpp__pyplusplus_wrapper
#define CBaseFlex_hpp__pyplusplus_wrapper

void register_CBaseFlex_class();

#endif//CBaseFlex_hpp__pyplusplus_wrapper

