// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef CBaseHandle_hpp__pyplusplus_wrapper
#define CBaseHandle_hpp__pyplusplus_wrapper

void register_CBaseHandle_class();

#endif//CBaseHandle_hpp__pyplusplus_wrapper

