// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef CBaseAnimating_hpp__pyplusplus_wrapper
#define CBaseAnimating_hpp__pyplusplus_wrapper

void register_CBaseAnimating_class();

#endif//CBaseAnimating_hpp__pyplusplus_wrapper

