// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef CBaseGrenade_hpp__pyplusplus_wrapper
#define CBaseGrenade_hpp__pyplusplus_wrapper

void register_CBaseGrenade_class();

#endif//CBaseGrenade_hpp__pyplusplus_wrapper

