// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef CPointEntity_hpp__pyplusplus_wrapper
#define CPointEntity_hpp__pyplusplus_wrapper

void register_CPointEntity_class();

#endif//CPointEntity_hpp__pyplusplus_wrapper

