// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#ifndef DeadEntity_hpp__pyplusplus_wrapper
#define DeadEntity_hpp__pyplusplus_wrapper

void register_DeadEntity_class();

#endif//DeadEntity_hpp__pyplusplus_wrapper

