// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#include "cbase.h"
#include "srcpy_entities.h"
#include "bone_setup.h"
#include "basegrenade_shared.h"
#include "SkyCamera.h"
#include "ai_basenpc.h"
#include "srcpy.h"
#include "tier0/memdbgon.h"
#include "IServerUnknown_pypp.hpp"

namespace bp = boost::python;

void register_IServerUnknown_class(){

    bp::class_< IServerUnknown, bp::bases< IHandleEntity >, boost::noncopyable >( "IServerUnknown", bp::no_init );

}

