//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ttscomp.rc
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDS_STRING3                     3
#define IDS_STRING4                     4
#define IDS_STRING5                     5
#define IDS_STRING6                     6
#define IDS_STRING7                     7
#define IDS_STRING8                     8
#define IDS_STRING9                     9
#define IDS_STRING10                    10
#define IDS_STRING11                    11
#define IDS_STRING12                    12
#define IDS_STRING13                    13
#define IDS_STRING14                    14
#define IDS_STRING15                    15
#define IDS_STRING16                    16
#define IDS_STRING17                    17
#define IDS_STRING18                    18
#define IDS_STRING19                    19
#define IDS_STRING20                    20
#define IDS_STRING21                    21
#define IDS_STRING22                    22
#define IDS_STRING23                    23
#define IDS_STRING24                    24
#define IDS_STRING25                    25
#define IDS_STRING26                    26
#define IDS_STRING27                    27
#define IDS_STRING28                    28
#define IDS_STRING29                    29
#define IDS_STRING30                    30
#define IDS_STRING31                    31
#define IDS_STRING32                    32
#define IDS_STRING33                    33
#define IDS_STRING34                    34
#define IDS_STRING35                    35
#define IDS_STRING36                    36
#define IDS_STRING37                    37
#define IDS_STRING38                    38
#define IDS_STRING39                    39
#define IDS_STRING40                    40
#define IDS_STRING41                    41
#define IDS_STRING42                    42
#define IDS_STRING43                    43
#define IDS_STRING44                    44
#define IDS_STRING45                    45
#define IDS_STRING46                    46
#define IDS_STRING47                    47
#define IDS_STRING48                    48
#define IDS_STRING49                    49
#define IDS_STRING50                    50
#define IDS_STRING51                    51
#define IDS_STRING52                    52
#define IDS_STRING53                    53
#define IDS_STRING54                    54
#define IDS_STRING55                    55
#define IDS_STRING56                    56
#define IDS_STRING57                    57
#define IDS_STRING58                    58
#define IDS_STRING59                    59
#define IDS_STRING60                    60
#define IDS_STRING61                    61
#define IDS_STRING62                    62
#define IDS_STRING63                    63
#define IDS_STRING64                    64
#define IDS_STRING65                    65
#define IDS_STRING66                    66
#define IDS_STRING67                    67
#define IDS_STRING68                    68
#define IDS_STRING69                    69
#define IDS_STRING70                    70
#define IDS_STRING71                    71
#define IDS_STRING72                    72
#define IDS_STRING73                    73
#define IDS_STRING74                    74
#define IDS_STRING75                    75
#define IDS_STRING76                    76
#define IDS_STRING77                    77
#define IDS_STRING78                    78
#define IDS_STRING79                    79
#define IDS_STRING81                    81
#define IDS_STRING82                    82
#define IDS_STRING83                    83
#define IDS_STRING84                    84
#define IDS_STRING85                    85
#define IDS_STRING86                    86
#define IDS_STRING87                    87
#define IDS_STRING88                    88
#define IDS_STRING89                    89
#define IDS_STRING90                    90
#define IDS_STRING91                    91
#define IDS_STRING92                    92
#define IDS_STRING93                    93
#define IDS_STRING94                    94
#define IDS_STRING95                    95
#define IDS_STRING96                    96
#define IDS_STRING97                    97
#define IDS_STRING98                    98
#define IDS_STRING99                    99
#define IDS_STRING100                   100
#define IDS_STRING101                   101
#define IDS_STRING102                   102
#define IDD_DIALOG1                     102
#define IDS_STRING103                   103
#define IDS_STRING104                   104
#define IDS_STRING105                   105
#define IDS_STRING106                   106
#define IDS_STRING107                   107
#define IDS_STRING108                   108
#define IDS_STRING109                   109
#define IDS_STRING110                   110
#define IDS_STRING111                   111
#define IDS_STRING112                   112
#define IDS_STRING113                   113
#define IDS_STRING114                   114
#define IDS_STRING115                   115
#define IDS_STRING116                   116
#define IDS_STRING117                   117
#define IDS_STRING118                   118
#define IDS_STRING119                   119
#define IDS_STRING120                   120
#define IDS_STRING121                   121
#define IDS_STRING122                   122

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
